version: 2.1
setup: true
orbs:
    path-filtering: circleci/path-filtering@1.1.0
workflows:
    generate-config:
        jobs:
          - path-filtering/filter:
              name: check_frontend_changes
              base-revision: main
              config-path: .circleci/continue_config.yml
              mapping: |
                apps/frontend/.* frontend-modified true
