version: 2.1

jobs:
    # sample checkout frontend
    checkout_frontend:
        docker:
            - image: cimg/node:18
        # working_directory: ~/
        steps:
            - checkout
            - run:
                name: Print frontend directory contents
                command: ls -la

workflows:
    test_checkout:
      jobs:
        - checkout_frontend